[tool.ruff]
line-length = 80
update-check = false
target-version = "py38"

select = [
  # isort
  "I",
  # pyflakes
  "F",
  # pycodestyle
  "E",
  "W",
  # flake8-2020
  "YTT",
  # flake8-bugbear
  "B",
  # flake8-quotes
  "Q",
  # flake8-comprehensions
  "C4",
  # pylint
  "PLC", "PLE", "PLR", "PLW", 
  # tidy imports
  "TID",
]

ignore = [
  # Magic number
  "PLR2004"
]
